webtalk_init -webtalk_dir /home/hieu/workspace/vhdl_pj_end/project_2/project_2.sim/sim_1/synth/timing/xsim/xsim.dir/tb_IntegralImage_time_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jun 11 19:32:02 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e14230b1-45db-4944-b38b-ad80e2eb0b11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "12a6a6522fd24cd5bac9fb14870d0a18" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496.007 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "53383688 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.80_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "140280_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2364478687 -regid "" -xml /home/hieu/workspace/vhdl_pj_end/project_2/project_2.sim/sim_1/synth/timing/xsim/xsim.dir/tb_IntegralImage_time_synth/webtalk/usage_statistics_ext_xsim.xml -html /home/hieu/workspace/vhdl_pj_end/project_2/project_2.sim/sim_1/synth/timing/xsim/xsim.dir/tb_IntegralImage_time_synth/webtalk/usage_statistics_ext_xsim.html -wdm /home/hieu/workspace/vhdl_pj_end/project_2/project_2.sim/sim_1/synth/timing/xsim/xsim.dir/tb_IntegralImage_time_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
