#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jun 11 21:33:22 +07 2025
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_IntegralImage_time_impl -key {Post-Implementation:sim_1:Timing:tb_IntegralImage} -tclbatch tb_IntegralImage.tcl -log simulate.log"
xsim tb_IntegralImage_time_impl -key {Post-Implementation:sim_1:Timing:tb_IntegralImage} -tclbatch tb_IntegralImage.tcl -log simulate.log

