#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Jun 11 19:28:27 +07 2025
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 12a6a6522fd24cd5bac9fb14870d0a18 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_IntegralImage_behav xil_defaultlib.tb_IntegralImage -log elaborate.log"
xelab -wto 12a6a6522fd24cd5bac9fb14870d0a18 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_IntegralImage_behav xil_defaultlib.tb_IntegralImage -log elaborate.log

